### ISSUE TITLE
why privileged?

### ISSUE THREAD

**Issue by Arthav24** [Kelebrimbor97/ROS-Docker#2]
I understand that the motivation was to have multiple ROS installations on the existing OS during the course time but at the same time in my opinion having flag `--priviliged` in a entry level document is kinda dangerous. This flag bypasses all the isolation and checks of linux kernel namespacing and thus having no shield from the host system. In all possibility a beginner can mess up the host system. It would be great to avoid this flag in all situation if possible. 

P.S. instead of build i suggest using buildx to build image steps in parallel and also multi stage builds

**Comment by Kelebrimbor97** [comment]
Hi @Arthav24 , the reason we have privileged is simple. Not many of the students that take this class are that experienced with software, so it is probably not a good idea for them to spend too much time with enabling very specific ports for any devices they may connect (which is something you will soon see towards the end of the class).

As for your second issue, I encourage you to create a pull request if there is a better way to build the image. The very reason of starting this repo was so people can pool their ideas and make something awesome that not only helps current students but the following batches as well!

**Comment by Kelebrimbor97** [comment]
Hi @Arthav24, the reason we have privileged is simple. Not many of the students that take this class are that experienced with software, so it is probably not a good idea for them to spend too much time with enabling very specific ports for any devices they may connect (which is something you will soon see towards the end of the class).

As for your second issue, I encourage you to create a pull request if there is a better way to build the image. The very reason of starting this repo was so people can pool their ideas and make something awesome that not only helps current students but the following batches as well!
